name: ddpg

defaults:
  - model: vanilla_ddpg

tau: 0.005 # target network update rate
discount_factor: 0.99 # discount factor
actor_lr: 0.0001 # learning rate for actor network
critic_lr: 0.0001 # learning rate for critic network
buffer_size: 1e6 # replay buffer size
expl_noise: 0.1 # std of Gaussian exploration noise
batch_size: 100
use_step_rate: false